//! Documentation registry for the Rhai scripting API.
//!
//! Single source of truth for the human-readable documentation of every
//! function registered on the script engine. `defs_gen` joins this table
//! with the live engine signatures to emit both the LSP definition file
//! (`rhai-defs/conchordal.d.rhai`) and the book API reference
//! (`docs/rhai_book/src/reference/api.md`). Integration tests enforce that
//! this table and the registered engine surface match exactly, so a new
//! `register_fn` without a doc entry (or a stale entry) fails CI.

/// Disambiguation key derived from the first parameter type.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Owner {
    /// Free function or scene-global verb (first param is not a handle type).
    Global,
    /// First param is `Material` or `Participant` (voice builder surface).
    Voice,
    /// First param is `Placement`.
    Placement,
    /// First param is `ModePattern`.
    ModePattern,
}

/// How the function is idiomatically called in scripts.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Style {
    /// `name(args)`.
    Free,
    /// `receiver.name(args)`.
    Method,
}

/// Behavior when called on a live (already spawned) `Participant`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Patch {
    /// Patches running voices when called on a live `Participant`.
    Live,
    /// Draft-only: ignored with a warning on a live `Participant`.
    Draft,
    /// Not a voice builder method.
    Na,
}

/// Progressive-disclosure tier of the scripting surface.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Tier {
    /// Curated composing surface; enough for every curated sample.
    Core,
    /// Candidate core verbs under audition: composing purpose, but
    /// research-grade stability until validated.
    Experimental,
    /// Mechanism-level fine tuning behind the core verbs.
    Tuning,
    /// For studying the instrument, not composing with it; weakest stability.
    Research,
}

/// Candidate core verbs under audition. Currently empty; expected first
/// inhabitants are incubating rhythm-shaping verbs (e.g. layer emphasis).
const EXPERIMENTAL_FNS: &[&str] = &[];

/// Mechanism-tuning functions. Everything not listed here or in
/// [`RESEARCH_FNS`] is `Tier::Core`. `defs_gen::check()` verifies that every
/// listed name exists in [`FN_DOCS`].
const TUNING_FNS: &[&str] = &[
    // placement
    "reject_targets",
    // phonation tiers 2/3
    "once",
    "while_alive",
    "adaptive_duration",
    "pulse_lock",
    "social",
    "duration_range",
    "duration_curve",
    "shorten_on_drop",
    "rhythm_freq",
    "rhythm_coupling_vitality",
    "rhythm_reward",
    // pitch movement mechanisms (hill-climb / peak-sampler)
    "pitch_smooth",
    "pitch_apply_mode",
    "landscape_weight",
    "exploration",
    "persistence",
    "anneal_temp",
    "temperature",
    "neighbor_step_cents",
    "improvement_threshold",
    "move_cost",
    "move_cost_exp",
    "proposal_interval",
    "tessitura_gravity",
    "window_cents",
    "top_k",
    "sigma_cents",
    "random_candidates",
    "global_peaks",
    "ratio_candidates",
    // neighbor awareness details
    "crowding_target",
    "octave_avoidance",
    "leave_self_out",
    "leave_self_out_harmonics",
    // lifecycle / respawn details
    "viability_scope",
    "respawn_min_c_level",
    "respawn_background_death_rate",
    // global psychoacoustic tuning
    "set_roughness_k",
    "set_global_coupling",
];

/// Research/assay controls. See [`TUNING_FNS`] for the tier rules.
const RESEARCH_FNS: &[&str] = &[
    "pitch_core",
    "move_cost_time_scale",
    "leave_self_out_mode",
    "selection_approx_loo",
    "set_pitch_objective",
    "set_control_update_mode",
    "set_scaffold_off",
    "set_scaffold_shared",
    "set_scaffold_scrambled",
];

pub fn tier_of(name: &str) -> Tier {
    if RESEARCH_FNS.contains(&name) {
        Tier::Research
    } else if TUNING_FNS.contains(&name) {
        Tier::Tuning
    } else if EXPERIMENTAL_FNS.contains(&name) {
        Tier::Experimental
    } else {
        Tier::Core
    }
}

pub fn tier_lists() -> impl Iterator<Item = (&'static str, Tier)> {
    EXPERIMENTAL_FNS
        .iter()
        .map(|n| (*n, Tier::Experimental))
        .chain(TUNING_FNS.iter().map(|n| (*n, Tier::Tuning)))
        .chain(RESEARCH_FNS.iter().map(|n| (*n, Tier::Research)))
}

pub struct FnDoc {
    pub name: &'static str,
    pub owner: Owner,
    pub category: &'static str,
    pub style: Style,
    pub patch: Patch,
    /// Usage variants without receiver (for methods) and without return type.
    /// Arities must cover the registered overload set exactly.
    pub usage: &'static [&'static str],
    /// One-line summary (LSP hover + reference lead line).
    pub summary: &'static str,
    /// Optional extra markdown (allowed values, defaults, caveats).
    pub details: &'static str,
}

pub struct CategoryDoc {
    pub id: &'static str,
    pub title: &'static str,
    pub intro: &'static str,
}

pub struct TypeDoc {
    pub name: &'static str,
    pub summary: &'static str,
}

pub struct ConstDoc {
    pub name: &'static str,
    pub ty: &'static str,
    pub summary: &'static str,
}

pub const TYPE_DOCS: &[TypeDoc] = &[
    TypeDoc {
        name: "Material",
        summary: "Voice template built from a constructor such as `sine()` or `harmonic()`; all builder methods are chainable.",
    },
    TypeDoc {
        name: "Participant",
        summary: "Handle to a placed voice group returned by `place()`; draft until the next `wait()`/`flush()`, then live.",
    },
    TypeDoc {
        name: "Placement",
        summary: "Where voices enter the field: built by `at()`, `peaks()`, `density()`, `random()`, or `line()`.",
    },
    TypeDoc {
        name: "ModePattern",
        summary: "Frequency pattern for modal synthesis bodies; built by `*_modes()` constructors.",
    },
    TypeDoc {
        name: "Bus",
        summary: "One of the two mono output buses; combine with `|` into a `BusSet`.",
    },
    TypeDoc {
        name: "BusSet",
        summary: "Combination of buses produced by `bus | bus`, accepted by `send()`.",
    },
];

pub const CONST_DOCS: &[ConstDoc] = &[
    ConstDoc {
        name: "habitat_bus",
        ty: "Bus",
        summary: "Analysis bus: NSGT -> landscape; what the ecology senses.",
    },
    ConstDoc {
        name: "presentation_bus",
        ty: "Bus",
        summary: "Presentation bus: cpal output, recording, UI metering; what the listener hears.",
    },
];

pub const CATEGORY_DOCS: &[CategoryDoc] = &[
    CategoryDoc {
        id: "materials",
        title: "Materials",
        intro: "Materials are voice templates. A constructor returns a `Material`; builder \
methods refine it; `place()` turns it into living voices.",
    },
    CategoryDoc {
        id: "placement",
        title: "Placement",
        intro: "Placements decide where voices enter the frequency field. Constructors return \
a `Placement`; modifiers refine it before it is passed to `place()`.",
    },
    CategoryDoc {
        id: "timeline",
        title: "Timeline & Staging",
        intro: "Staging verbs commit voices and move script time. `place()` stages a draft \
`Participant`; `wait()`/`flush()` commit drafts; scopes release groups automatically.",
    },
    CategoryDoc {
        id: "body",
        title: "Body & Timbre",
        intro: "Sound body parameters of a voice: level, spectrum, detuning, and envelope.",
    },
    CategoryDoc {
        id: "phonation",
        title: "Phonation & Rhythm",
        intro: "When and how long a voice sounds. Tier 1 picks a region on the rhythm \
coupling continuum (`metric()`, `entrained()`, `flow()`); Tier 2 sets explicit when/duration; \
Tier 3 is expert tuning. Calls on the same axis are last-write-wins, and modifiers are \
remembered and applied when their matching preset is selected.",
    },
    CategoryDoc {
        id: "pitch",
        title: "Pitch Movement",
        intro: "How a voice moves through the consonance field. `seek_consonance()` plus \
`glide()` is the curated surface; the rest tunes the hill-climb and peak-sampler mechanisms.",
    },
    CategoryDoc {
        id: "neighbors",
        title: "Neighbor Awareness",
        intro: "How a voice perceives other voices and its own spectral footprint when \
evaluating the field.",
    },
    CategoryDoc {
        id: "lifecycle",
        title: "Lifecycle & Viability",
        intro: "Energy budget and survival. Viability makes field fit matter over time: \
`consonance_viability()` defines the consonance window and `viability_rate()` controls \
continuous recharge, with environment-relative scoring by default.",
    },
    CategoryDoc {
        id: "respawn",
        title: "Respawn",
        intro: "Population turnover. A respawn policy decides where replacements appear when \
voices die; capacity and acceptance thresholds shape ecology-scale behavior.",
    },
    CategoryDoc {
        id: "modes",
        title: "Mode Patterns",
        intro: "Frequency relationships for `modal()` bodies. Constructors return a \
`ModePattern`; modifiers are chainable. Landscape-aware patterns sample the live field.",
    },
    CategoryDoc {
        id: "routing",
        title: "Routing",
        intro: "Each voice contributes to two independent mono buses: the presentation bus \
(the work as heard) and the habitat bus (what the ecology senses through NSGT analysis). \
By default a voice feeds both.",
    },
    CategoryDoc {
        id: "director",
        title: "Director & Global Parameters",
        intro: "Scene-global terrain shaping and research controls. Director verbs are soft \
priors: they shape the terrain and never schedule a beat or force a measure.",
    },
];

pub const FN_DOCS: &[FnDoc] = &[
    // --- materials ---
    FnDoc {
        name: "sine",
        owner: Owner::Global,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["sine()"],
        summary: "Material with a pure sine body.",
        details: "",
    },
    FnDoc {
        name: "harmonic",
        owner: Owner::Global,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["harmonic()"],
        summary: "Material with a harmonic-series body.",
        details: "",
    },
    FnDoc {
        name: "modal",
        owner: Owner::Global,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["modal()"],
        summary: "Material with a resonator-based modal body; shape it with `modes()`.",
        details: "",
    },
    FnDoc {
        name: "saw",
        owner: Owner::Global,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["saw()"],
        summary: "Harmonic-body preset with brightness 0.85.",
        details: "",
    },
    FnDoc {
        name: "square",
        owner: Owner::Global,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["square()"],
        summary: "Harmonic-body preset with brightness 0.65.",
        details: "",
    },
    FnDoc {
        name: "noise",
        owner: Owner::Global,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["noise()"],
        summary: "Harmonic-body preset with brightness 1.0 and motion 1.0.",
        details: "",
    },
    FnDoc {
        name: "variant",
        owner: Owner::Voice,
        category: "materials",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["variant(material)"],
        summary: "Clone a material so the copy can be modified independently.",
        details: "",
    },
    // --- placement ---
    FnDoc {
        name: "at",
        owner: Owner::Global,
        category: "placement",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["at(freq_hz)"],
        summary: "Place at a fixed frequency in Hz.",
        details: "",
    },
    FnDoc {
        name: "peaks",
        owner: Owner::Global,
        category: "placement",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["peaks(root_hz)"],
        summary: "Place at high Consonance Field positions around a root.",
        details: "Default multiplier range is 1x-4x of the root (see `range()`) with 1.0 ERB \
spacing (see `spacing()`).",
    },
    FnDoc {
        name: "density",
        owner: Owner::Global,
        category: "placement",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["density(min_hz, max_hz)"],
        summary: "Sample positions from Consonance Density inside a frequency range.",
        details: "Density is a normalized distribution derived from the consonance model and \
remains well-defined inside the requested range. Default spacing is 1.0 ERB.",
    },
    FnDoc {
        name: "random",
        owner: Owner::Global,
        category: "placement",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["random(min_hz, max_hz)"],
        summary: "Log-uniform random placement inside a frequency range.",
        details: "",
    },
    FnDoc {
        name: "line",
        owner: Owner::Global,
        category: "placement",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["line(start_hz, end_hz)"],
        summary: "Linear interpolation of positions between two frequencies.",
        details: "",
    },
    FnDoc {
        name: "count",
        owner: Owner::Placement,
        category: "placement",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["count(n)"],
        summary: "Number of voices to place (default 1).",
        details: "",
    },
    FnDoc {
        name: "range",
        owner: Owner::Placement,
        category: "placement",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["range(min_mul, max_mul)"],
        summary: "Multiplier range relative to the root; only valid on `peaks()`.",
        details: "",
    },
    FnDoc {
        name: "spacing",
        owner: Owner::Placement,
        category: "placement",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["spacing(min_erb)"],
        summary: "Minimum ERB distance between placed voices; valid on `peaks()` and `density()`.",
        details: "",
    },
    FnDoc {
        name: "reject_targets",
        owner: Owner::Placement,
        category: "placement",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["reject_targets(anchor_hz, targets_st, exclusion_st, max_tries)"],
        summary: "Reject sampled positions near specified semitone targets.",
        details: "`targets_st` is an array of semitone offsets from `anchor_hz`, `exclusion_st` \
is the exclusion zone width in semitones, and `max_tries` is the retry limit. Wraps any \
strategy-bearing placement (`peaks()`, `density()`, `random()`, `line()`).",
    },
    // --- timeline ---
    FnDoc {
        name: "place",
        owner: Owner::Voice,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Draft,
        usage: &["place(material, placement)"],
        summary: "Stage a Participant at the current script time.",
        details: "Committed by the next `wait()` or `flush()`. Until then, builder methods on \
the returned `Participant` shape the initial spawn; afterwards, live-patchable methods update \
running voices. Calling `place(participant, placement)` on a draft re-places it (sets \
frequency, count, and strategy).",
    },
    FnDoc {
        name: "wait",
        owner: Owner::Global,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["wait(seconds)"],
        summary: "Commit pending drafts, then advance the timeline cursor.",
        details: "",
    },
    FnDoc {
        name: "flush",
        owner: Owner::Global,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["flush()"],
        summary: "Commit pending drafts without advancing time.",
        details: "",
    },
    FnDoc {
        name: "release",
        owner: Owner::Voice,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["release(participant)"],
        summary: "Release a live group; its voices enter their release phase and fade out.",
        details: "",
    },
    FnDoc {
        name: "section",
        owner: Owner::Global,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["section(name, callback)"],
        summary: "Named scope; groups placed inside are released when the callback returns.",
        details: "",
    },
    FnDoc {
        name: "play",
        owner: Owner::Global,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &[
            "play(callback)",
            "play(callback, arg1)",
            "play(callback, arg1, arg2)",
            "play(callback, arg1, arg2, arg3)",
            "play(callback, [args])",
        ],
        summary: "Scoped callback execution with automatic group release.",
        details: "Accepts 0-3 positional arguments, or an array of arguments.",
    },
    FnDoc {
        name: "parallel",
        owner: Owner::Global,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["parallel(callbacks)"],
        summary: "Run an array of closures on parallel timelines from the current cursor.",
        details: "Each branch starts at the current cursor; the cursor advances to the latest \
branch end.",
    },
    FnDoc {
        name: "seed",
        owner: Owner::Global,
        category: "timeline",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["seed(value)"],
        summary: "Set the random seed for reproducible scenarios.",
        details: "",
    },
    // --- body ---
    FnDoc {
        name: "amp",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["amp(value)"],
        summary: "Amplitude in 0.0-1.0.",
        details: "",
    },
    FnDoc {
        name: "freq",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["freq(hz)"],
        summary: "Frequency lock in Hz; implies an anchored pitch (see `anchor()`).",
        details: "",
    },
    FnDoc {
        name: "brightness",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["brightness(value)"],
        summary: "Spectral brightness in 0.0-1.0 (harmonic/modal bodies).",
        details: "",
    },
    FnDoc {
        name: "spread",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["spread(value)"],
        summary: "Detuning spread.",
        details: "",
    },
    FnDoc {
        name: "unison",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["unison(count)"],
        summary: "Number of unison detuning copies.",
        details: "",
    },
    FnDoc {
        name: "modes",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["modes(pattern)"],
        summary: "Set the mode pattern of a modal body.",
        details: "See the Mode Patterns section for constructors and modifiers.",
    },
    FnDoc {
        name: "adsr",
        owner: Owner::Voice,
        category: "body",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["adsr(attack_sec, decay_sec, sustain_level, release_sec)"],
        summary: "ADSR amplitude envelope.",
        details: "",
    },
    // --- phonation ---
    FnDoc {
        name: "brain",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["brain(name)"],
        summary: "Articulation brain: `\"entrain\"` (default), `\"seq\"`, or `\"drone\"`.",
        details: "`entrain` synchronizes with detected rhythms in the field, `seq` does \
fixed-duration note sequencing, `drone` sustains with slow frequency sway.",
    },
    FnDoc {
        name: "sustain",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["sustain()"],
        summary: "Sustain phonation mode (default).",
        details: "",
    },
    FnDoc {
        name: "repeat",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["repeat()"],
        summary: "Repeated/pulsed phonation mode.",
        details: "",
    },
    FnDoc {
        name: "metric",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["metric()"],
        summary: "High coupling to the shared emergent meter: deep attractor, stable pulse.",
        details: "Takes no rate argument: the tempo region is director-level terrain \
(`temporal_basin`).",
    },
    FnDoc {
        name: "entrained",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["entrained()"],
        summary: "Medium coupling: synchronization emerges over time, still drifts.",
        details: "",
    },
    FnDoc {
        name: "flow",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["flow()"],
        summary: "Near-zero coupling: free renewal process, non-metric texture.",
        details: "",
    },
    FnDoc {
        name: "entrainment",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["entrainment(strength)"],
        summary: "Override coupling strength in 0-1 (free .. locked).",
        details: "Order-independent with presets: `entrainment(0.8).metric()` and \
`metric().entrainment(0.8)` are equivalent.",
    },
    FnDoc {
        name: "rhythm_role",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["rhythm_role(name)"],
        summary: "Metrical job: `\"beat\"`, `\"subdivision\"`, `\"accent\"`, or `\"texture\"`.",
        details: "`accent` emits a stronger onset that drives the shared meter harder, so a \
recurring downbeat can seed an emergent measure.",
    },
    FnDoc {
        name: "microtiming",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["microtiming(amount)"],
        summary: "Signed beat-phase offset in -0.5..0.5; 0.5 reads as syncopation.",
        details: "",
    },
    FnDoc {
        name: "once",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["once()"],
        summary: "Single trigger.",
        details: "",
    },
    FnDoc {
        name: "pulse",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["pulse(rate_hz)"],
        summary: "Pulse at an explicit rate in Hz.",
        details: "",
    },
    FnDoc {
        name: "while_alive",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["while_alive()"],
        summary: "Hold/sustain until release.",
        details: "",
    },
    FnDoc {
        name: "cycles",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["cycles(n)"],
        summary: "Duration of n rhythm cycles.",
        details: "",
    },
    FnDoc {
        name: "adaptive_duration",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["adaptive_duration()"],
        summary: "Duration follows field support.",
        details: "",
    },
    FnDoc {
        name: "pulse_lock",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["pulse_lock(depth)"],
        summary: "Low-level pulse phase weighting in 0-1.",
        details: "",
    },
    FnDoc {
        name: "social",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["social(coupling)"],
        summary: "Social coupling for `entrained()` or `pulse()`, in 0-1.",
        details: "",
    },
    FnDoc {
        name: "duration_range",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["duration_range(min_cycles, max_cycles)"],
        summary: "Adaptive duration range in rhythm cycles.",
        details: "",
    },
    FnDoc {
        name: "duration_curve",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["duration_curve(k, x0)"],
        summary: "Adaptive duration curve parameters.",
        details: "",
    },
    FnDoc {
        name: "shorten_on_drop",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["shorten_on_drop(gain)"],
        summary: "Shorten adaptive duration when field support drops.",
        details: "",
    },
    FnDoc {
        name: "rhythm_freq",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["rhythm_freq(freq_hz)"],
        summary: "Internal theta/rhythm oscillator frequency.",
        details: "",
    },
    FnDoc {
        name: "rhythm_coupling_vitality",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["rhythm_coupling_vitality(lambda_v, v_floor)"],
        summary: "Vitality-modulated rhythm coupling.",
        details: "",
    },
    FnDoc {
        name: "rhythm_reward",
        owner: Owner::Voice,
        category: "phonation",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["rhythm_reward(rho_t, metric)"],
        summary: "Energy reward for timing fit; metric is `\"attack_phase_match\"` or `\"none\"`.",
        details: "",
    },
    // --- pitch ---
    FnDoc {
        name: "anchor",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["anchor()"],
        summary: "Hold the voice at its pitch: an anchored voice never moves.",
        details: "Voices placed with `at()` or given `freq()` are anchored implicitly; use \
`anchor()` to hold strategy-placed voices (`peaks()`, `density()`, ...) at their settled \
position, or to state the intent explicitly.",
    },
    FnDoc {
        name: "seek_consonance",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["seek_consonance()"],
        summary: "Free hill-climb movement toward better field positions, with glide defaults.",
        details: "How pitch decisions land is resolved at commit unless `pitch_apply_mode()` \
was called: sustained voices glide, re-attacking voices (`pulse()`, `metric()`, \
`entrained()`, `flow()`) snap at onsets.",
    },
    FnDoc {
        name: "glide",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["glide(tau_sec)"],
        summary: "Pitch glide time constant in seconds.",
        details: "",
    },
    FnDoc {
        name: "pitch_smooth",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["pitch_smooth(tau_sec)"],
        summary: "Pitch smoothing time constant in seconds.",
        details: "",
    },
    FnDoc {
        name: "pitch_core",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["pitch_core(name)"],
        summary: "`\"hill_climb\"` or `\"peak_sampler\"`. Research control.",
        details: "",
    },
    FnDoc {
        name: "pitch_apply_mode",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["pitch_apply_mode(name)"],
        summary: "`\"gate_snap\"` or `\"glide\"`: override how pitch decisions are applied.",
        details: "Without an explicit call, moving voices resolve this at commit from their \
phonation: sustained voices glide, re-attacking voices snap at onsets.",
    },
    FnDoc {
        name: "landscape_weight",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["landscape_weight(value)"],
        summary: "Weight of the landscape objective.",
        details: "",
    },
    FnDoc {
        name: "exploration",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["exploration(value)"],
        summary: "Exploration tendency of the hill-climb.",
        details: "",
    },
    FnDoc {
        name: "persistence",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["persistence(value)"],
        summary: "Persistence bias of the hill-climb.",
        details: "",
    },
    FnDoc {
        name: "anneal_temp",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["anneal_temp(value)"],
        summary: "Annealing temperature of the hill-climb.",
        details: "",
    },
    FnDoc {
        name: "temperature",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["temperature(value)"],
        summary: "Selection temperature of the peak sampler (softness of candidate choice).",
        details: "",
    },
    FnDoc {
        name: "neighbor_step_cents",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["neighbor_step_cents(value)"],
        summary: "Step size for neighbor exploration in cents.",
        details: "",
    },
    FnDoc {
        name: "improvement_threshold",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["improvement_threshold(value)"],
        summary: "Minimum improvement to accept a move.",
        details: "",
    },
    FnDoc {
        name: "move_cost",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["move_cost(coeff)"],
        summary: "Cost multiplier for pitch changes.",
        details: "",
    },
    FnDoc {
        name: "move_cost_exp",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["move_cost_exp(exp)"],
        summary: "Exponent for the move cost.",
        details: "",
    },
    FnDoc {
        name: "move_cost_time_scale",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["move_cost_time_scale(name)"],
        summary: "`\"legacy\"`/`\"integration_window\"` or `\"proposal\"`/`\"proposal_interval\"`.",
        details: "",
    },
    FnDoc {
        name: "proposal_interval",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["proposal_interval(seconds)"],
        summary: "Proposal generation interval in seconds.",
        details: "",
    },
    FnDoc {
        name: "tessitura_gravity",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["tessitura_gravity(value)"],
        summary: "Gravity toward the tessitura center.",
        details: "",
    },
    FnDoc {
        name: "window_cents",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["window_cents(width)"],
        summary: "Peak-sampler search window width in cents.",
        details: "",
    },
    FnDoc {
        name: "top_k",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["top_k(count)"],
        summary: "Number of top candidates kept by the peak sampler.",
        details: "",
    },
    FnDoc {
        name: "sigma_cents",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["sigma_cents(spread)"],
        summary: "Gaussian spread of the peak sampler in cents.",
        details: "",
    },
    FnDoc {
        name: "random_candidates",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["random_candidates(count)"],
        summary: "Number of random candidates considered.",
        details: "",
    },
    FnDoc {
        name: "global_peaks",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["global_peaks(count)", "global_peaks(count, min_sep_cents)"],
        summary: "Global field peaks as movement candidates, with optional minimum separation.",
        details: "",
    },
    FnDoc {
        name: "ratio_candidates",
        owner: Owner::Voice,
        category: "pitch",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["ratio_candidates(count)"],
        summary: "Ratio-based movement candidates; 0 disables.",
        details: "",
    },
    // --- neighbors ---
    FnDoc {
        name: "avoid_neighbors",
        owner: Owner::Voice,
        category: "neighbors",
        style: Style::Method,
        patch: Patch::Live,
        usage: &[
            "avoid_neighbors(strength)",
            "avoid_neighbors(strength, sigma_cents)",
        ],
        summary: "Crowding repulsion from neighboring voices.",
        details: "With one argument the repulsion width is derived from the roughness kernel; \
the two-argument form sets it explicitly in cents.",
    },
    FnDoc {
        name: "octave_avoidance",
        owner: Owner::Voice,
        category: "neighbors",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["octave_avoidance(weight)"],
        summary: "Repel octave/unison doubling so voices settle on distinct chord tones.",
        details: "Adds an octave-equivalence (chroma) term to the occupancy field shared by \
crowding and adaptation. 0 leaves octaves free to converge; higher weights push voices off \
octave-doublings toward distinct pitches. Pairs with avoid_neighbors, which only repels \
near-unison.",
    },
    FnDoc {
        name: "crowding_target",
        owner: Owner::Voice,
        category: "neighbors",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["crowding_target(same_visible, other_visible)"],
        summary: "Which voices are visible to crowding: own group, other groups (booleans).",
        details: "",
    },
    FnDoc {
        name: "leave_self_out",
        owner: Owner::Voice,
        category: "neighbors",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["leave_self_out(enabled)"],
        summary: "Subtract the voice's own spectral contribution when evaluating the field.",
        details: "",
    },
    FnDoc {
        name: "leave_self_out_mode",
        owner: Owner::Voice,
        category: "neighbors",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["leave_self_out_mode(name)"],
        summary: "`\"approx\"`/`\"approx_harmonics\"` or `\"exact\"`/`\"exact_scan\"`.",
        details: "",
    },
    FnDoc {
        name: "leave_self_out_harmonics",
        owner: Owner::Voice,
        category: "neighbors",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["leave_self_out_harmonics(count)"],
        summary: "Number of harmonics used for approximate self-subtraction.",
        details: "",
    },
    // --- lifecycle ---
    FnDoc {
        name: "metabolism",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["metabolism(rate)"],
        summary: "Energy consumption rate.",
        details: "",
    },
    FnDoc {
        name: "initial_energy",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["initial_energy(value)"],
        summary: "Starting energy.",
        details: "",
    },
    FnDoc {
        name: "energy_cap",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["energy_cap(value)"],
        summary: "Maximum energy after recharge/reward.",
        details: "",
    },
    FnDoc {
        name: "recharge_rate",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["recharge_rate(rate)"],
        summary: "Energy gained per attack.",
        details: "",
    },
    FnDoc {
        name: "action_cost",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["action_cost(cost)"],
        summary: "Energy cost per attack.",
        details: "",
    },
    FnDoc {
        name: "sustain_drive",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Live,
        usage: &["sustain_drive(value)"],
        summary: "Continuous drive level for sustained voices.",
        details: "",
    },
    FnDoc {
        name: "viability_rate",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["viability_rate(rate)"],
        summary: "Continuous consonance-driven energy recharge rate.",
        details: "",
    },
    FnDoc {
        name: "consonance_viability",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["consonance_viability(low, high)"],
        summary: "Consonance window used for viability scoring.",
        details: "Enables environment-relative scoring by default: a voice is evaluated against \
the field with its own footprint approximately removed (see `viability_scope()`).",
    },
    FnDoc {
        name: "viability_scope",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["viability_scope(name)"],
        summary: "`\"environment\"` (default) or `\"total\"` viability scoring scope.",
        details: "Use `\"total\"` only when the selection question should include the voice's \
own contribution.",
    },
    FnDoc {
        name: "dissonance_cost",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["dissonance_cost(cost)"],
        summary: "Extra energy cost at low consonance.",
        details: "",
    },
    FnDoc {
        name: "selection_approx_loo",
        owner: Owner::Voice,
        category: "lifecycle",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["selection_approx_loo(enabled)"],
        summary: "Override environment-relative viability scoring; research/reference control.",
        details: "Material only. Use only for older reference assays that need the previous \
implementation-level control.",
    },
    // --- respawn ---
    FnDoc {
        name: "respawn_random",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_random()"],
        summary: "Respawn at random locations.",
        details: "",
    },
    FnDoc {
        name: "respawn_hereditary",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_hereditary(sigma_oct)"],
        summary: "Hereditary respawn with frequency variance in octaves.",
        details: "",
    },
    FnDoc {
        name: "respawn_consonance",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_consonance()"],
        summary: "Respawn from consonance-biased parental peaks.",
        details: "",
    },
    FnDoc {
        name: "respawn_capacity",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_capacity(count)"],
        summary: "Maintain population up to a capacity.",
        details: "",
    },
    FnDoc {
        name: "respawn_settle",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_settle(placement)"],
        summary: "Placement used for replacements.",
        details: "Requires a strategy-bearing placement: `density()`, `peaks()`, `random()`, or \
`line()` (not `at()`).",
    },
    FnDoc {
        name: "respawn_min_c_level",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_min_c_level(level)"],
        summary: "Minimum consonance level for respawn acceptance.",
        details: "",
    },
    FnDoc {
        name: "respawn_background_death_rate",
        owner: Owner::Voice,
        category: "respawn",
        style: Style::Method,
        patch: Patch::Draft,
        usage: &["respawn_background_death_rate(rate)"],
        summary: "Background turnover rate per second.",
        details: "",
    },
    // --- modes ---
    FnDoc {
        name: "harmonic_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["harmonic_modes()"],
        summary: "Harmonic series: f, 2f, 3f, ...",
        details: "",
    },
    FnDoc {
        name: "odd_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["odd_modes()"],
        summary: "Odd harmonics: f, 3f, 5f, ...",
        details: "",
    },
    FnDoc {
        name: "power_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["power_modes(beta)"],
        summary: "Power law: f * n^beta.",
        details: "",
    },
    FnDoc {
        name: "stiff_string_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["stiff_string_modes(stiffness)"],
        summary: "Stiffness-adjusted harmonics.",
        details: "",
    },
    FnDoc {
        name: "custom_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["custom_modes(ratios)"],
        summary: "Custom frequency ratios from an array.",
        details: "",
    },
    FnDoc {
        name: "modal_table",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["modal_table(name)"],
        summary: "Named mode table lookup.",
        details: "Falls back to `harmonic_modes()` with a warning if the name is unknown.",
    },
    FnDoc {
        name: "landscape_density_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["landscape_density_modes()"],
        summary: "Modes sampled from the live landscape density.",
        details: "",
    },
    FnDoc {
        name: "landscape_peaks_modes",
        owner: Owner::Global,
        category: "modes",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["landscape_peaks_modes()"],
        summary: "Modes sampled from live landscape peaks.",
        details: "",
    },
    FnDoc {
        name: "count",
        owner: Owner::ModePattern,
        category: "modes",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["count(n)"],
        summary: "Number of modes.",
        details: "",
    },
    FnDoc {
        name: "range",
        owner: Owner::ModePattern,
        category: "modes",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["range(min_mul, max_mul)"],
        summary: "Frequency range; only valid on `landscape_*_modes()`.",
        details: "",
    },
    FnDoc {
        name: "spacing",
        owner: Owner::ModePattern,
        category: "modes",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["spacing(min_erb)"],
        summary: "Minimum ERB distance between modes; only valid on `landscape_*_modes()`.",
        details: "",
    },
    FnDoc {
        name: "gamma",
        owner: Owner::ModePattern,
        category: "modes",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["gamma(g)"],
        summary: "Density sharpening exponent; only valid on `landscape_density_modes()`.",
        details: "",
    },
    FnDoc {
        name: "jitter",
        owner: Owner::ModePattern,
        category: "modes",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["jitter(cents)"],
        summary: "Randomize mode frequencies by up to the given cents.",
        details: "",
    },
    FnDoc {
        name: "seed",
        owner: Owner::ModePattern,
        category: "modes",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["seed(value)"],
        summary: "Random seed for jittered patterns (>= 0).",
        details: "",
    },
    // --- routing ---
    FnDoc {
        name: "send",
        owner: Owner::Voice,
        category: "routing",
        style: Style::Method,
        patch: Patch::Na,
        usage: &["send(bus)"],
        summary: "Route the voice to specific buses; accepts a `Bus` or a `BusSet`.",
        details: "Material only. `send(habitat_bus)` makes a voice sensed by the ecology but \
absent from the presented sound; `send(presentation_bus)` is heard without perturbing the \
ecology; `send(habitat_bus | presentation_bus)` feeds both (the default).",
    },
    // --- director ---
    FnDoc {
        name: "harmonic_mirror",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["harmonic_mirror(value)"],
        summary: "Harmonic-tension dial in 0.0-1.0: blends the harmonicity terrain from overtone toward undertone projection.",
        details: "Raising it degrades the terrain's coherence for overtone-radiating bodies, \
heard as harmonic tension; lowering it restores consonant gravity. It is a tension-release \
axis, not a tonality (major/minor) switch.",
    },
    FnDoc {
        name: "meter_stability",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["meter_stability(value)"],
        summary: "Attractor depth in 0-1: how readily a pulse forms.",
        details: "A soft prior: it only deepens the basin for a real periodicity; it never \
fabricates a beat from non-metric input.",
    },
    FnDoc {
        name: "temporal_basin",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["temporal_basin(min_hz, max_hz)"],
        summary: "Tempo region the emergent beat gravitates toward.",
        details: "The time-axis analogue of `density(min, max)`: it shapes the terrain, does \
not place a beat, and never forces a measure.",
    },
    FnDoc {
        name: "set_roughness_k",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_roughness_k(value)"],
        summary: "Roughness tolerance of the landscape.",
        details: "",
    },
    FnDoc {
        name: "set_global_coupling",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_global_coupling(value)"],
        summary: "Voice interaction strength.",
        details: "",
    },
    FnDoc {
        name: "set_pitch_objective",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_pitch_objective(name)"],
        summary: "`\"consonance\"`/`\"positive\"` or `\"dissonance\"`/`\"negative\"`. Research control.",
        details: "",
    },
    FnDoc {
        name: "set_control_update_mode",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_control_update_mode(name)"],
        summary: "`\"snapshot_phased\"`/`\"snapshot\"` (default) or `\"sequential_rotating\"`/`\"sequential\"`. Research control.",
        details: "",
    },
    FnDoc {
        name: "set_scaffold_off",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_scaffold_off()"],
        summary: "Disable the external rhythm scaffold.",
        details: "Scaffolds are external comparison controls for demos and assays, not the \
rhythm-composition abstraction.",
    },
    FnDoc {
        name: "set_scaffold_shared",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_scaffold_shared(freq_hz)"],
        summary: "Shared external scaffold pulse.",
        details: "",
    },
    FnDoc {
        name: "set_scaffold_scrambled",
        owner: Owner::Global,
        category: "director",
        style: Style::Free,
        patch: Patch::Na,
        usage: &["set_scaffold_scrambled(freq_hz, seed)"],
        summary: "Per-voice scrambled scaffold pulse.",
        details: "",
    },
];
